### ISSUE TITLE
Make Tutorials Page Dynamic

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#497]
Different clients have different requirements from one another. We need to be able to update the tutorials page on a deploy-by-deploy basis using Docker volumes.

Changes required:

- [ ] Small modification to tutorials header to use a single `<section>` for the header tiles and `flex-wrap` instead of having two secions
- [ ] Replace repeated blocks in the header tiles section with a single iterated template, using the data structure below.
- [ ] Replace repeated blocks in the accordion section with a single iterated template, using the data structure below.
- [ ] Pull data from an external file which can be injected through docker volumes (@cjol)

Data structure:
```typescript
Array<
    {
        id: string,
        icon: string,
        tile: {
            title: string,
            comment: string
        },
        accordion: {
            title: string,
            htmlContent ?: string,
           // omit the slide demo if this is undefined
            tutorialData ?: Array<{
                slideSrc: string,
                slideRatio: string,
                // N.B. there's a typo in the current code which reads targetPosision
                targetPosition: {x: number, y: number},
                slideText: string
            }>
        }
    }
>
```

**Comment by brunosmm** [comment]
@cjol some questions...
- how do we handle localizations? title and comment are a localize string which we should call the localization system or will be the value direct we needed to add to the page?
- Should we think of something to request JSON files in different languages? like tutorials_en-gb.json?
- PHP server-side will deliver the JSON file if we request it? What we should call to get the file? url/tutorial.json?

**Comment by cjol** [comment]
I was hoping you wouldn't ask about localization ;) I think for now we can ignore localizations because we only have one language per deployment right now. I think having a suffix on the file is probably the right approach. 

The JSON file will be hosted from the static directory so PHP doesn't need to touch it. We'll need to fetch the JSON dynamically with e.g. axios. You can see how I'm doing it in the locale PR here: #478. If you can get it to the stage where there's ons JS object that's used to drive the interface, I can take it from there to extract it into a remote JSON file.
